"""Database models for devices, ESP32 telemetry events, and Cowrie logs."""

from __future__ import annotations

from datetime import datetime, timezone

from database import db


def utc_now() -> datetime:
    """Return a timezone-aware UTC timestamp for model defaults."""

    return datetime.now(timezone.utc)


class Device(db.Model):
    """Registered IoT device that can report defensive telemetry."""

    __tablename__ = "devices"

    id: int = db.Column(db.Integer, primary_key=True)
    device_name: str = db.Column(db.String(120), nullable=False, unique=True, index=True)
    device_ip: str = db.Column(db.String(45), nullable=False)
    status: str = db.Column(db.String(30), nullable=False, default="unknown")
    created_at: datetime = db.Column(db.DateTime(timezone=True), default=utc_now)

    def to_dict(self) -> dict[str, object]:
        """Serialize the model for API responses."""

        return {
            "id": self.id,
            "device_name": self.device_name,
            "device_ip": self.device_ip,
            "status": self.status,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


class Event(db.Model):
    """Telemetry event generated by an ESP32 device or related lab source."""

    __tablename__ = "events"

    id: int = db.Column(db.Integer, primary_key=True)
    timestamp: datetime = db.Column(db.DateTime(timezone=True), default=utc_now, index=True)
    source_ip: str = db.Column(db.String(45), nullable=True, index=True)
    event_type: str = db.Column(db.String(80), nullable=False, index=True)
    severity: str = db.Column(db.String(30), nullable=False, default="info", index=True)
    payload: str = db.Column(db.Text, nullable=False)
    device_name: str = db.Column(db.String(120), nullable=False, index=True)

    def to_dict(self) -> dict[str, object]:
        """Serialize the model for API responses and Socket.IO payloads."""

        return {
            "id": self.id,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "source_ip": self.source_ip,
            "event_type": self.event_type,
            "severity": self.severity,
            "payload": self.payload,
            "device_name": self.device_name,
        }


class CowrieEvent(db.Model):
    """Log event parsed from Cowrie JSON telemetry on the Kali VM."""

    __tablename__ = "cowrie_events"

    id: int = db.Column(db.Integer, primary_key=True)
    timestamp: datetime = db.Column(db.DateTime(timezone=True), default=utc_now, index=True)
    source_ip: str = db.Column(db.String(45), nullable=True, index=True)
    username: str = db.Column(db.String(120), nullable=True)
    eventid: str = db.Column(db.String(120), nullable=False, index=True)
    raw_json: str = db.Column(db.Text, nullable=False)

    def to_dict(self) -> dict[str, object]:
        """Serialize the model for dashboard and API consumers."""

        return {
            "id": self.id,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "source_ip": self.source_ip,
            "username": self.username,
            "eventid": self.eventid,
            "raw_json": self.raw_json,
        }
